replicaCount: 1
image:
  repository: prbreaker/performance-service
  tag: 872364406cfbf1b0ea8dbf2a331c2c8360b90f66
  pullPolicy: Always
port: 5000
nodePort: 30004
bypassAuth: "false"
env:
  identityServiceUrl: "http://identity-service:5000"
  workoutServiceUrl: "http://workout-service:5000"
db:
  url: "postgresql+psycopg2://performance_user:performance_password@performance-db:5432/performance_db"
