replicaCount: 1
image:
  repository: prbreaker/identity-service
  tag: f2100823d0c82b6fa1fba71be4c36a6a4d4fe0cd
  pullPolicy: Always
port: 5000
nodePort: 30001
env:
  workoutServiceUrl: "http://workout-service:5000"
db:
  url: "postgresql+psycopg2://identity_user:identity_password@identity-db:5432/identity_db"
jwtSecret: "super-secret-change-me"
