apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  PORT:                 "5000"
  IDENTITY_SERVICE_URL: {{ .Values.env.identityServiceUrl | quote }}
  WORKOUT_SERVICE_URL:  {{ .Values.env.workoutServiceUrl | quote }}
  WGROUPS_SERVICE_URL:  {{ .Values.env.wgroupsServiceUrl | quote }}
