replicaCount: 1
image:
  repository: prbreaker/api-gateway
  tag: f2100823d0c82b6fa1fba71be4c36a6a4d4fe0cd
  pullPolicy: Always
port: 5000
nodePort: 30000
env:
  identityServiceUrl: "http://identity-service:5000"
  workoutServiceUrl: "http://workout-service:5000"
  wgroupsServiceUrl: "http://workoutgroups-service:5000"
  performanceServiceUrl: "http://performance-service:5000"
  corsAllowOrigins: ""
