apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  PORT:                "5000"
  WORKOUT_SERVICE_URL: {{ .Values.env.workoutServiceUrl | quote }}
