apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  JWT_SECRET:   {{ .Values.jwtSecret | default "super-secret-change-me" | quote }}
  DATABASE_URL: {{ .Values.db.url | quote }}
