replicaCount: 1
image:
  repository: prbreaker/workout-service
  tag: 872364406cfbf1b0ea8dbf2a331c2c8360b90f66
  pullPolicy: Always
port: 5000
nodePort: 30002
env:
  identityServiceUrl: "http://identity-service:5000"
db:
  url: "postgresql+psycopg2://workout_user:workout_password@workout-db:5432/workout_db"
global:
  jwtSecret: "super-secret-change-me"
