replicaCount: 1
image:
  repository: prbreaker/workout-service
  tag: latest
  pullPolicy: Always
port: 5000
nodePort: 30002
env:
  identityServiceUrl: "http://identity-service:5000"
db:
  url: "postgresql+psycopg2://workout_user:workout_password@workout-db:5432/workout_db"
